// bob tries to register as a offer_hosting twice
// author has no additional actions
module.exports = [
  { "name": "alice", "actions": ["register", "request_hosting", "offer_hosting"] },
  { "name": "bob", "actions": ["register", "offer_hosting"] },
  { "name": "charlie", "actions": ["register", "offer_hosting"] },
  { "name": "dave", "actions": ["register", "offer_hosting"] },
  { "name": "eve", "actions": ["register", "author_hypercore", "offer_hosting"] },
  { "name": "janice", "actions": ["register", "offer_hosting"] },
  { "name": "ferdie", "actions": ["register", "offer_hosting"] },
  { "name": "one", "actions": ["register", "offer_hosting"] },
  { "name": "two", "actions": ["register", "offer_hosting"] },
  { "name": "tom", "actions": ["register", "offer_hosting"] },
  { "name": "ashley", "actions": ["register", "offer_hosting"] },
  { "name": "emma", "actions": ["register", "offer_hosting"] },
  { "name": "joe", "actions": ["register", "offer_hosting"] },
  { "name": "anna", "actions": ["register", "offer_hosting"] },
  { "name": "paul", "actions": ["register", "offer_hosting"] },
  { "name": "rachel", "actions": ["register", "offer_hosting"] },
  { "name": "alfie", "actions": ["register", "offer_hosting"] },
  { "name": "poppy", "actions": ["register", "offer_hosting"] },
]

// { "name": "iva", "actions": ["register", "offer_hosting"] },
// { "name": "luigi", "actions": ["register", "offer_hosting"] },
// { "name": "rok", "actions": ["register", "offer_hosting"] },
// { "name": "bianca", "actions": ["register", "offer_hosting"] },
// { "name": "bent", "actions": ["register", "offer_hosting"] },
// { "name": "felix", "actions": ["register", "offer_hosting"] },
// { "name": "elfi", "actions": ["register", "offer_hosting"] },
// { "name": "clemens", "actions": ["register", "offer_hosting"] },
