// bob tries to register as a hoster twice
// author has no additional roles
module.exports = [
  { "name": "alice", "roles": ["peer", "sponsor", "worker"] },
  { "name": "bob", "roles": ["peer", "worker"] },
  { "name": "charlie", "roles": ["peer", "worker"] },
  { "name": "dave", "roles": ["peer", "worker"] },
  { "name": "eve", "roles": ["author"] },
  { "name": "janice", "roles": ["peer", "worker"] },
  { "name": "ferdie", "roles": ["peer", "worker"] },
  { "name": "one", "roles": ["peer", "worker"] },
  { "name": "two", "roles": ["peer", "worker"] },
  { "name": "tom", "roles": ["peer", "worker"] },
  { "name": "ashley", "roles": ["peer", "worker"] },
  { "name": "emma", "roles": ["peer", "worker"] },
  { "name": "joe", "roles": ["peer", "worker"] },
  { "name": "anna", "roles": ["peer", "worker"] },
  { "name": "paul", "roles": ["peer", "worker"] },
  { "name": "rachel", "roles": ["peer", "worker"] },
  { "name": "alfie", "roles": ["peer", "worker"] },
  { "name": "poppy", "roles": ["peer", "worker"] },
]

// { "name": "iva", "roles": ["peer", "worker"] },
// { "name": "luigi", "roles": ["peer", "worker"] },
// { "name": "rok", "roles": ["peer", "worker"] },
// { "name": "bianca", "roles": ["peer", "worker"] },
// { "name": "bent", "roles": ["peer", "worker"] },
// { "name": "felix", "roles": ["peer", "worker"] },
// { "name": "elfi", "roles": ["peer", "worker"] },
// { "name": "clemens", "roles": ["peer", "worker"] },
